// <auto-generated />
using System;
using KaukoBskyFeeds.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaukoBskyFeeds.Db.Migrations
{
    [DbContext(typeof(FeedDbContext))]
    [Migration("20241104090908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("KaukoBskyFeeds.Db.Models.Post", b =>
                {
                    b.Property<string>("Did")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rkey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Langs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.HasKey("Did", "Rkey");

                    b.HasIndex("EventTime");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("KaukoBskyFeeds.Db.Models.Post", b =>
                {
                    b.OwnsOne("KaukoBskyFeeds.Db.Models.PostEmbeds", "Embeds", b1 =>
                        {
                            b1.Property<string>("PostDid")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostRkey")
                                .HasColumnType("TEXT");

                            b1.HasKey("PostDid", "PostRkey");

                            b1.ToTable("Posts");

                            b1.ToJson("Embeds");

                            b1.WithOwner()
                                .HasForeignKey("PostDid", "PostRkey");

                            b1.OwnsMany("KaukoBskyFeeds.Db.Models.PostEmbedImage", "Images", b2 =>
                                {
                                    b2.Property<string>("PostEmbedsPostDid")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("PostEmbedsPostRkey")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("MimeType")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RefLink")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("PostEmbedsPostDid", "PostEmbedsPostRkey", "Id");

                                    b2.ToTable("Posts");

                                    b2.WithOwner()
                                        .HasForeignKey("PostEmbedsPostDid", "PostEmbedsPostRkey");
                                });

                            b1.Navigation("Images");
                        });

                    b.OwnsOne("KaukoBskyFeeds.Db.Models.PostReply", "Reply", b1 =>
                        {
                            b1.Property<string>("PostDid")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostRkey")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Parent")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Root")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PostDid", "PostRkey");

                            b1.ToTable("Posts");

                            b1.ToJson("Reply");

                            b1.WithOwner()
                                .HasForeignKey("PostDid", "PostRkey");
                        });

                    b.Navigation("Embeds");

                    b.Navigation("Reply");
                });
#pragma warning restore 612, 618
        }
    }
}
